---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: An inference service of ${{ values.owner | default('guest')}}
  annotations:
    backstage.io/kubernetes-namespace: "${{values.namespace}}"
spec:
  type: InferenceService
  lifecycle: dev
  owner: ${{ values.owner | default('guest')}}
